version: 2.1

jobs:
  lint-build:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install application dependencies
          command: |
            python3 -m venv devops
            . devops/bin/activate
            make install
      - run:
          name: lint application code
          command: |
            . devops/bin/activate
            make lint
      - save_cache:
          paths:
            - ./devops
          key: v1-dependencies-{{ checksum "requirements.txt" }}
workflows:
  default:
    jobs:
    - lint-build
