- name: "Configure cluster"
  hosts: management[0]
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
  roles:
    - cluster-deployment
    - cluster-service