- name: "Deploy app image"
  hosts: management[0]
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
    CIRCLE_WORKFLOW_ID: "{{ lookup('env', 'CIRCLE_WORKFLOW_ID') }}"
  tasks:
    - name: Update deployment to run latest Build
      shell: "./bin/kubectl set image deployments/{{ ENVIRONMENT_NAME }}-deployment {{ ENVIRONMENT_NAME }}-app=sakshi781996/{{ ENVIRONMENT_NAME }}:{{ CIRCLE_WORKFLOW_ID }}"
      args:
        chdir: $HOME

    - name: Check deployment status
      shell: "./bin/kubectl rollout status deployments/{{ ENVIRONMENT_NAME }}-deployment"
      args:
        chdir: $HOME